//go:build ignore

// Command gen marshals Go's unicode package tables into gs/unicode/tables.ts as
// pure numeric data. The gs/unicode override constructs RangeTable/CaseRange
// objects and runs Go's lookup algorithms over this data, so the override stays
// byte-faithful to the Go reference across all of Unicode. Regenerate after a Go
// (Unicode version) bump with:  go run gen.go > tables.ts
package main

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"unicode"
)

func main() {
	var b strings.Builder
	b.WriteString("// Code generated by gen.go; DO NOT EDIT.\n")
	b.WriteString("// Unicode " + unicode.Version + " tables marshaled from Go's unicode package.\n")
	b.WriteString("// Pure numeric data with no imports; gs/unicode/unicode.ts builds the objects.\n\n")
	b.WriteString("export type RangeData = [Array<[number, number, number]>, Array<[number, number, number]>, number]\n\n")

	writeTableMap(&b, "categoryData", toStringMap(unicode.Categories))
	writeTableMap(&b, "scriptData", toStringMap(unicode.Scripts))
	writeTableMap(&b, "propertyData", toStringMap(unicode.Properties))
	writeTableMap(&b, "foldCategoryData", toStringMap(unicode.FoldCategory))
	writeTableMap(&b, "foldScriptData", toStringMap(unicode.FoldScript))

	writeCaseRanges(&b, "caseRangeData", unicode.CaseRanges)
	writeCaseRanges(&b, "turkishCaseData", []unicode.CaseRange(unicode.TurkishCase))

	writeAsciiFold(&b)
	writeCaseOrbit(&b)
	writeLatin1Props(&b)

	if _, err := os.Stdout.WriteString(b.String()); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func toStringMap(m map[string]*unicode.RangeTable) map[string]*unicode.RangeTable {
	return m
}

func sortedKeys(m map[string]*unicode.RangeTable) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func writeTableMap(b *strings.Builder, name string, m map[string]*unicode.RangeTable) {
	fmt.Fprintf(b, "export const %s: Record<string, RangeData> = {\n", name)
	for _, k := range sortedKeys(m) {
		fmt.Fprintf(b, "  %q: %s,\n", k, rangeTable(m[k]))
	}
	b.WriteString("}\n\n")
}

func rangeTable(t *unicode.RangeTable) string {
	var r16 strings.Builder
	r16.WriteByte('[')
	for i, r := range t.R16 {
		if i > 0 {
			r16.WriteByte(',')
		}
		fmt.Fprintf(&r16, "[0x%x,0x%x,%d]", r.Lo, r.Hi, r.Stride)
	}
	r16.WriteByte(']')

	var r32 strings.Builder
	r32.WriteByte('[')
	for i, r := range t.R32 {
		if i > 0 {
			r32.WriteByte(',')
		}
		fmt.Fprintf(&r32, "[0x%x,0x%x,%d]", r.Lo, r.Hi, r.Stride)
	}
	r32.WriteByte(']')

	return fmt.Sprintf("[%s,%s,%d]", r16.String(), r32.String(), t.LatinOffset)
}

func writeCaseRanges(b *strings.Builder, name string, ranges []unicode.CaseRange) {
	fmt.Fprintf(b, "export const %s: Array<[number, number, number, number, number]> = [\n", name)
	for _, cr := range ranges {
		fmt.Fprintf(b, "  [0x%x,0x%x,%d,%d,%d],\n", cr.Lo, cr.Hi, int32(cr.Delta[0]), int32(cr.Delta[1]), int32(cr.Delta[2]))
	}
	b.WriteString("]\n\n")
}

func writeAsciiFold(b *strings.Builder) {
	b.WriteString("export const asciiFold: number[] = [")
	for r := rune(0); r <= unicode.MaxASCII; r++ {
		if r > 0 {
			b.WriteByte(',')
		}
		fmt.Fprintf(b, "0x%x", unicode.SimpleFold(r))
	}
	b.WriteString("]\n\n")
}

// writeCaseOrbit reconstructs Go's unexported caseOrbit table: every rune above
// ASCII whose SimpleFold result differs from the plain case-toggle fallback is an
// orbit entry. Go's SimpleFold consults this exact set before the case fallback.
func writeCaseOrbit(b *strings.Builder) {
	b.WriteString("export const caseOrbitData: Array<[number, number]> = [\n")
	for r := rune(unicode.MaxASCII + 1); r <= unicode.MaxRune; r++ {
		fold := unicode.SimpleFold(r)
		if fold == foldFallback(r) {
			continue
		}
		fmt.Fprintf(b, "  [0x%x,0x%x],\n", r, fold)
	}
	b.WriteString("]\n\n")
}

func foldFallback(r rune) rune {
	if l := unicode.ToLower(r); l != r {
		return l
	}
	return unicode.ToUpper(r)
}

// Latin1 property bits; these must stay in sync with the L1_* constants in
// unicode.ts. The table captures Go's predicate results for U+0000..U+00FF so the
// Latin1 fast paths match Go exactly without re-deriving its property masks.
const (
	l1Control = 1 << 0
	l1Letter  = 1 << 1
	l1Upper   = 1 << 2
	l1Lower   = 1 << 3
	l1Title   = 1 << 4
	l1Number  = 1 << 5
	l1Digit   = 1 << 6
	l1Mark    = 1 << 7
	l1Punct   = 1 << 8
	l1Symbol  = 1 << 9
	l1Space   = 1 << 10
	l1Graphic = 1 << 11
	l1Print   = 1 << 12
)

func writeLatin1Props(b *strings.Builder) {
	b.WriteString("export const latin1Props: number[] = [")
	for r := rune(0); r <= unicode.MaxLatin1; r++ {
		if r > 0 {
			b.WriteByte(',')
		}
		var bits int
		if unicode.IsControl(r) {
			bits |= l1Control
		}
		if unicode.IsLetter(r) {
			bits |= l1Letter
		}
		if unicode.IsUpper(r) {
			bits |= l1Upper
		}
		if unicode.IsLower(r) {
			bits |= l1Lower
		}
		if unicode.IsTitle(r) {
			bits |= l1Title
		}
		if unicode.IsNumber(r) {
			bits |= l1Number
		}
		if unicode.IsDigit(r) {
			bits |= l1Digit
		}
		if unicode.IsMark(r) {
			bits |= l1Mark
		}
		if unicode.IsPunct(r) {
			bits |= l1Punct
		}
		if unicode.IsSymbol(r) {
			bits |= l1Symbol
		}
		if unicode.IsSpace(r) {
			bits |= l1Space
		}
		if unicode.IsGraphic(r) {
			bits |= l1Graphic
		}
		if unicode.IsPrint(r) {
			bits |= l1Print
		}
		fmt.Fprintf(b, "0x%x", bits)
	}
	b.WriteString("]\n")
}
