// Generated file based on slice.go
// Updated when compliance tests are re-run, DO NOT EDIT!

import * as $ from "@goscript/builtin/index.ts"

export async function main(): Promise<void> {
	$.println("--- Original Tests ---")
	let s = $.makeSlice<number>(5, 10, "number")
	$.println($.len(s))
	$.println($.cap(s))
	let s2 = $.makeSlice<string>(3, undefined, "string")
	$.println($.len(s2))
	$.println($.cap(s2))
	s[0] = 10
	s[4] = 20
	s2[1] = "hello"
	$.println(s[0])
	$.println(s[4])
	$.println(s2[1])
	$.println("--- New Tests ---")
	let arrLit = [1, 2, 3, 4, 5]
	let sliceFromLit = $.goSlice(arrLit, undefined, undefined)
	$.println($.len(sliceFromLit))
	$.println($.cap(sliceFromLit))
	$.println(sliceFromLit[0])
	$.println(sliceFromLit[4])
	let arrVar = ["a", "b", "c", "d"]
	let sliceFromVar = $.goSlice(arrVar, undefined, undefined)
	$.println($.len(sliceFromVar))
	$.println($.cap(sliceFromVar))
	$.println(sliceFromVar[0])
	$.println(sliceFromVar[3])
	let sliceIndices = $.goSlice(arrVar, 1, 3)
	$.println($.len(sliceIndices))
	$.println($.cap(sliceIndices))
	$.println(sliceIndices[0])
	$.println(sliceIndices[1])
	$.println("--- Zero len/cap append ---")
	let zeroSlice = $.makeSlice<number>(0, 0, "number")
	$.println($.len(zeroSlice))
	$.println($.cap(zeroSlice))
	zeroSlice = $.append(zeroSlice, 100)
	$.println($.len(zeroSlice))
	$.println($.cap(zeroSlice))
	$.println(zeroSlice[0])
	zeroSlice = $.append(zeroSlice, 200)
	$.println($.len(zeroSlice))
	$.println($.cap(zeroSlice))
	$.println(zeroSlice[1])
	$.println("--- Modify slice, check array ---")
	let modArr = [10, 20, 30]
	let modSlice = $.goSlice(modArr, undefined, undefined)
	modSlice[1] = 25
	$.println(modArr[1])
	$.println(modSlice[1])
	$.println("--- Modify array, check slice ---")
	modArr[0] = 15
	$.println(modArr[0])
	$.println(modSlice[0])
	$.println("--- Append sub-slice w/in capacity ---")
	let appendArr = [1, 2, 3, 4, 5]
	let appendSlice1 = $.goSlice(appendArr, 0, 2)
	$.println($.len(appendSlice1))
	$.println($.cap(appendSlice1))
	let appendSlice2 = $.append(appendSlice1, 99)
	$.println($.len(appendSlice2))
	$.println($.cap(appendSlice2))
	$.println(appendSlice2[2])
	$.println(appendArr[2])
	$.println("--- Append sub-slice exceed capacity ---")
	let appendSlice3 = $.goSlice(appendArr, 3, 5)
	$.println($.len(appendSlice3))
	$.println($.cap(appendSlice3))
	let appendSlice4 = $.append(appendSlice3, 101)
	$.println($.len(appendSlice4))
	$.println($.cap(appendSlice4))
	$.println(appendSlice4[0])
	$.println(appendSlice4[1])
	$.println(appendSlice4[2])
	$.println(appendArr[0])
	$.println(appendArr[1])
	$.println(appendArr[2])
	$.println(appendArr[3])
	$.println(appendArr[4])
	$.println("--- Slicing a slice ---")
	let baseSlice = [0, 10, 20, 30, 40, 50]
	let subSlice1 = $.goSlice(baseSlice, 1, 4)
	$.println($.len(subSlice1))
	$.println($.cap(subSlice1))
	$.println(subSlice1[0])
	let subSlice2 = $.goSlice(subSlice1, 1, 3)
	$.println($.len(subSlice2))
	$.println($.cap(subSlice2))
	$.println(subSlice2[0])
	$.println(subSlice2[1])
	subSlice2[0] = 22
	$.println(subSlice1[1])
	$.println(baseSlice[2])
	$.println("--- Three-index slicing ---")
	let threeIndexArr = [0, 1, 2, 3, 4, 5]
	let threeIndexSlice = $.goSlice(threeIndexArr, 1, 3, 4)
	$.println($.len(threeIndexSlice))
	$.println($.cap(threeIndexSlice))
	$.println(threeIndexSlice[0])
	$.println(threeIndexSlice[1])
	threeIndexSlice = $.append(threeIndexSlice, 99)
	$.println($.len(threeIndexSlice))
	$.println($.cap(threeIndexSlice))
	$.println(threeIndexSlice[2])
	$.println(threeIndexArr[3])
	threeIndexSlice = $.append(threeIndexSlice, 101)
	$.println($.len(threeIndexSlice))
	$.println($.cap(threeIndexSlice))
	$.println(threeIndexSlice[3])
	$.println(threeIndexArr[4])
	$.println("--- Additional Tests ---")
	let sliceLiteral = [10, 20, 30]
	$.println("Slice literal len:", $.len(sliceLiteral))
	$.println("Slice literal cap:", $.cap(sliceLiteral))
	$.println("Slice literal[1]:", sliceLiteral[1])
	let nilSlice: $.Slice<number> = null
	$.println("Nil slice len:", $.len(nilSlice))
	$.println("Nil slice cap:", $.cap(nilSlice))
	nilSlice = $.append(nilSlice, 5)
	$.println("Append to nil slice len:", $.len(nilSlice))
	$.println("Append to nil slice cap:", $.cap(nilSlice))
	$.println("Append to nil slice[0]:", nilSlice[0])
	$.println("--- Slices of Slices Tests ---")
	let sliceOfSlices = [[1, 2, 3], [4, 5], [6, 7, 8, 9]]
	$.println("Length of sliceOfSlices:", $.len(sliceOfSlices))
	$.println("Capacity of sliceOfSlices:", $.cap(sliceOfSlices))
	$.println("sliceOfSlices[0][1]:", sliceOfSlices[0][1])
	$.println("sliceOfSlices[1][0]:", sliceOfSlices[1][0])
	$.println("sliceOfSlices[2][3]:", sliceOfSlices[2][3])
	$.println("--- Append to inner slice ---")
	let innerSlice = sliceOfSlices[1]
	$.println("Length of innerSlice:", $.len(innerSlice))
	$.println("Capacity of innerSlice:", $.cap(innerSlice))
	innerSlice = $.append(innerSlice, 50)
	$.println("Length of innerSlice after append:", $.len(innerSlice))
	$.println("Capacity of innerSlice after append:", $.cap(innerSlice))
	$.println("innerSlice[2]:", innerSlice[2])
	let sliceOfSlicesWithCap = [[1, 2, 3], $.makeSlice<number>(2, 5, "number"), [6, 7, 8, 9]]
	sliceOfSlicesWithCap[1][0] = 40
	sliceOfSlicesWithCap[1][1] = 50
	$.println("--- Append to inner slice with capacity ---")
	let innerSliceWithCap = sliceOfSlicesWithCap[1]
	$.println("Length of innerSliceWithCap:", $.len(innerSliceWithCap))
	$.println("Capacity of innerSliceWithCap:", $.cap(innerSliceWithCap))
	innerSliceWithCap = $.append(innerSliceWithCap, 60)
	$.println("Length of innerSliceWithCap after append:", $.len(innerSliceWithCap))
	$.println("Capacity of innerSliceWithCap after append:", $.cap(innerSliceWithCap))
	$.println("innerSliceWithCap[2]:", innerSliceWithCap[2])
	$.println("sliceOfSlicesWithCap[1][2]:", $.goSlice(sliceOfSlicesWithCap[1], undefined, 3)[2])
	$.println("--- Append to inner slice exceeding capacity ---")
	let innerSliceExceedCap = sliceOfSlices[0]
	$.println("Length of innerSliceExceedCap:", $.len(innerSliceExceedCap))
	$.println("Capacity of innerSliceExceedCap:", $.cap(innerSliceExceedCap))
	innerSliceExceedCap = $.append(innerSliceExceedCap, 10, 20)
	$.println("Length of innerSliceExceedCap after append:", $.len(innerSliceExceedCap))
	$.println("Capacity of innerSliceExceedCap after append:", $.cap(innerSliceExceedCap))
	$.println("innerSliceExceedCap[3]:", innerSliceExceedCap[3])
	$.println("innerSliceExceedCap[4]:", innerSliceExceedCap[4])
	$.println("Original sliceOfSlices[0] after inner append:", sliceOfSlices[0][0], sliceOfSlices[0][1], sliceOfSlices[0][2])
	$.println("--- Slicing a slice of slices ---")
	let subSliceOfSlices = $.goSlice(sliceOfSlices, 1, 3)
	$.println("Length of subSliceOfSlices:", $.len(subSliceOfSlices))
	$.println("Capacity of subSliceOfSlices:", $.cap(subSliceOfSlices))
	$.println("subSliceOfSlices[0][0]:", subSliceOfSlices[0][0])
	$.println("subSliceOfSlices[1][2]:", subSliceOfSlices[1][2])
	$.println("--- Modify element in sub-slice of slices ---")
	subSliceOfSlices[0][1] = 55
	$.println("sliceOfSlices[1][1] after sub-slice modification:", sliceOfSlices[1][1])
	$.println("--- Append a new slice to slice of slices ---")
	sliceOfSlices = $.append(sliceOfSlices, [100, 110])
	$.println("Length of sliceOfSlices after append:", $.len(sliceOfSlices))
	$.println("Capacity of sliceOfSlices after append:", $.cap(sliceOfSlices))
	$.println("sliceOfSlices[3][0]:", sliceOfSlices[3][0])
	$.println("--- Append an existing slice to slice of slices ---")
	let existingSlice = [200, 210]
	sliceOfSlices = $.append(sliceOfSlices, existingSlice)
	$.println("Length of sliceOfSlices after appending existing:", $.len(sliceOfSlices))
	$.println("Capacity of sliceOfSlices after appending existing:", $.cap(sliceOfSlices))
	$.println("sliceOfSlices[4][1]:", sliceOfSlices[4][1])
	$.println("--- Modify appended existing slice ---")
	existingSlice[0] = 205
	$.println("sliceOfSlices[4][0] after modifying existingSlice:", sliceOfSlices[4][0])
	$.println("--- Modify slice within sliceOfSlices ---")
	sliceOfSlices[4][1] = 215
	$.println("existingSlice[1] after modifying slice within sliceOfSlices:", existingSlice[1])
	$.println("--- Make slice of slices ---")
	let makeSliceOfSlices = $.makeSlice<$.Slice<number>>(2, 4)
	$.println("Length of makeSliceOfSlices:", $.len(makeSliceOfSlices))
	$.println("Capacity of makeSliceOfSlices:", $.cap(makeSliceOfSlices))
	makeSliceOfSlices[0] = [1000, 2000]
	makeSliceOfSlices[1] = $.makeSlice<number>(1, 3, "number")
	makeSliceOfSlices[1][0] = 3000
	$.println("makeSliceOfSlices[0][1]:", makeSliceOfSlices[0][1])
	$.println("makeSliceOfSlices[1][0]:", makeSliceOfSlices[1][0])
	makeSliceOfSlices = $.append(makeSliceOfSlices, [4000, 5000])
	$.println("Length of makeSliceOfSlices after append:", $.len(makeSliceOfSlices))
	$.println("Capacity of makeSliceOfSlices after append:", $.cap(makeSliceOfSlices))
	$.println("makeSliceOfSlices[2][1]:", makeSliceOfSlices[2][1])
	makeSliceOfSlices = $.append(makeSliceOfSlices, [6000])
	$.println("Length of makeSliceOfSlices after second append:", $.len(makeSliceOfSlices))
	$.println("Capacity of makeSliceOfSlices after second append:", $.cap(makeSliceOfSlices))
	$.println("makeSliceOfSlices[3][0]:", makeSliceOfSlices[3][0])
	$.println("--- Nil slice of slices ---")
	let nilSliceOfSlices: $.Slice<$.Slice<number>> = null
	$.println("Nil slice of slices len:", $.len(nilSliceOfSlices))
	$.println("Nil slice of slices cap:", $.cap(nilSliceOfSlices))
	nilSliceOfSlices = $.append(nilSliceOfSlices, [10000])
	$.println("Length of nilSliceOfSlices after append:", $.len(nilSliceOfSlices))
	$.println("Capacity of nilSliceOfSlices after append:", $.cap(nilSliceOfSlices))
	$.println("nilSliceOfSlices[0][0]:", nilSliceOfSlices[0][0])
	nilSliceOfSlices = $.append(nilSliceOfSlices, [20000, 30000])
	$.println("Length of nilSliceOfSlices after second append:", $.len(nilSliceOfSlices))
	$.println("Capacity of nilSliceOfSlices after second append:", $.cap(nilSliceOfSlices))
	$.println("nilSliceOfSlices[1][1]:", nilSliceOfSlices[1][1])
	$.println("--- Empty slice of slices ---")
	let emptySliceOfSlices = $.makeSlice<$.Slice<number>>(0)
	$.println("Empty slice of slices len:", $.len(emptySliceOfSlices))
	$.println("Empty slice of slices cap:", $.cap(emptySliceOfSlices))
	emptySliceOfSlices = $.append(emptySliceOfSlices, [40000])
	$.println("Length of emptySliceOfSlices after append:", $.len(emptySliceOfSlices))
	$.println("Capacity of emptySliceOfSlices after append:", $.cap(emptySliceOfSlices))
	$.println("emptySliceOfSlices[0][0]:", emptySliceOfSlices[0][0])
}


if ($.isMainScript(import.meta)) {
	await main()
}
